import { getLoadedChannelPlugin } from "../../channels/plugins/index.js";
import { normalizeAnyChannelId } from "../../channels/registry.js";
import type { OpenClawConfig } from "../../config/types.openclaw.js";
import { resolveOutboundChannelPlugin } from "./channel-resolution.js";

/** A channel/account whose outbound renderer receives the turn's visible text. */
export type DeliveryFormatRoute = {
  channel?: string | null;
  accountId?: string | null;
};

type DeliveryFormatVia = "reply" | "message_tool";

const DELIVERY_FORMAT_LEAD: Record<DeliveryFormatVia, string> = {
  reply:
    "The JSON below is generated by OpenClaw. Your visible output for this turn is delivered to this channel; follow its response_format.",
  message_tool:
    "The JSON below is generated by OpenClaw. Text you send to this channel with the message tool is rendered by it; follow its response_format.",
};

/** Renders one channel account's formatting contract; only delivered runs bootstrap. */
export function buildDeliveryFormatPrompt(params: {
  cfg: OpenClawConfig;
  route: DeliveryFormatRoute;
  via?: DeliveryFormatVia;
  agentId?: string;
  allowBootstrap?: boolean;
}): string | undefined {
  const channel = params.route.channel;
  if (!channel) {
    return undefined;
  }
  const plugin = params.allowBootstrap
    ? resolveOutboundChannelPlugin({
        channel,
        cfg: params.cfg,
        agentId: params.agentId,
        allowBootstrap: true,
      })
    : getLoadedChannelPlugin(normalizeAnyChannelId(channel) ?? channel);
  // The plugin answers for the exact account that will render the text, so an
  // account-level capability (for example Telegram rich messages) cannot leak.
  const responseFormat = plugin?.agentPrompt?.inboundFormattingHints?.({
    cfg: params.cfg,
    accountId: params.route.accountId?.trim() || undefined,
  });
  if (!plugin || !responseFormat) {
    return undefined;
  }
  const payload = {
    schema: "openclaw.delivery_format.v1",
    channel: plugin.id,
    response_format: responseFormat,
  };
  return [
    "### Delivery Format",
    DELIVERY_FORMAT_LEAD[params.via ?? "reply"],
    "",
    "```json",
    JSON.stringify(payload, null, 2),
    "```",
    "",
  ].join("\n");
}

/**
 * Picks the route whose contract governs a background turn's visible text: the
 * final-reply route when one exists, else the message tool's default route.
 */
export async function resolveTurnDeliveryFormatPrompt(params: {
  cfg: OpenClawConfig;
  agentId?: string;
  /** Where final visible replies are delivered (announce, `--deliver`). */
  reply?: DeliveryFormatRoute;
  /** Present only when the turn can use the message tool. */
  messageTool?: DeliveryFormatRoute;
}): Promise<string | undefined> {
  if (params.reply?.channel) {
    return buildDeliveryFormatPrompt({
      cfg: params.cfg,
      route: params.reply,
      agentId: params.agentId,
      allowBootstrap: true,
    });
  }
  if (!params.messageTool) {
    return undefined;
  }
  // Same default the message tool applies to a send without `channel`; with
  // several configured channels there is no default and no contract to pick.
  // Loaded lazily: reply turns import this module, and channel selection pulls
  // configured-plugin discovery that only background turns need.
  const channel =
    params.messageTool.channel ??
    (await import("./channel-selection.runtime.js")
      .then(({ resolveMessageChannelSelection }) =>
        resolveMessageChannelSelection({ cfg: params.cfg, agentId: params.agentId }),
      )
      .then((selection) => selection.channel)
      .catch(() => undefined));
  return buildDeliveryFormatPrompt({
    cfg: params.cfg,
    route: { channel, accountId: params.messageTool.accountId },
    via: "message_tool",
    agentId: params.agentId,
    allowBootstrap: true,
  });
}
