/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiCliRouteImport } from './routes/api/cli'
import { Route as ApiHooksWhatsappRouteImport } from './routes/api/hooks/whatsapp'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCliRoute = ApiCliRouteImport.update({
  id: '/api/cli',
  path: '/api/cli',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHooksWhatsappRoute = ApiHooksWhatsappRouteImport.update({
  id: '/api/hooks/whatsapp',
  path: '/api/hooks/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/cli': typeof ApiCliRoute
  '/api/hooks/whatsapp': typeof ApiHooksWhatsappRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/cli': typeof ApiCliRoute
  '/api/hooks/whatsapp': typeof ApiHooksWhatsappRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/cli': typeof ApiCliRoute
  '/api/hooks/whatsapp': typeof ApiHooksWhatsappRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/cli' | '/api/hooks/whatsapp'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/cli' | '/api/hooks/whatsapp'
  id: '__root__' | '/' | '/api/cli' | '/api/hooks/whatsapp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiCliRoute: typeof ApiCliRoute
  ApiHooksWhatsappRoute: typeof ApiHooksWhatsappRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cli': {
      id: '/api/cli'
      path: '/api/cli'
      fullPath: '/api/cli'
      preLoaderRoute: typeof ApiCliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hooks/whatsapp': {
      id: '/api/hooks/whatsapp'
      path: '/api/hooks/whatsapp'
      fullPath: '/api/hooks/whatsapp'
      preLoaderRoute: typeof ApiHooksWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiCliRoute: ApiCliRoute,
  ApiHooksWhatsappRoute: ApiHooksWhatsappRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
