export const browserCoreExamples = [
  "paddy browser status",
  "paddy browser start",
  "paddy browser start --headless",
  "paddy browser stop",
  "paddy browser tabs",
  "paddy browser open https://example.com",
  "paddy browser focus abcd1234",
  "paddy browser close abcd1234",
  "paddy browser screenshot",
  "paddy browser screenshot --full-page",
  "paddy browser screenshot --ref 12",
  "paddy browser snapshot",
  "paddy browser snapshot --format aria --limit 200",
  "paddy browser snapshot --efficient",
  "paddy browser snapshot --labels",
];

export const browserActionExamples = [
  "paddy browser navigate https://example.com",
  "paddy browser resize 1280 720",
  "paddy browser click 12 --double",
  "paddy browser click-coords 120 340",
  'paddy browser type 23 "hello" --submit',
  "paddy browser press Enter",
  "paddy browser hover 44",
  "paddy browser drag 10 11",
  "paddy browser select 9 OptionA OptionB",
  "paddy browser upload /tmp/openclaw/uploads/file.pdf",
  "paddy browser upload media://inbound/file.pdf",
  'paddy browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "paddy browser dialog --accept",
  'paddy browser wait --text "Done"',
  "paddy browser evaluate --fn '(el) => el.textContent' --ref 7",
  "paddy browser evaluate --fn 'const title = document.title; return title;'",
  "paddy browser console --level error",
  "paddy browser pdf",
  "paddy browser batch --actions-file plan.json",
  'paddy browser batch --actions \'[{"kind":"wait","timeMs":500},{"kind":"click","ref":"12"},{"kind":"type","ref":"23","text":"hello"}]\'',
  "paddy browser batch --actions-file plan.json --continue",
];
